language: node_js
node_js:
  - "8"
  - "6"
  - "7"
  - "10"
  
os:
  - linux
  
env:
  - NODE_ENV=test
    JSONSYN_ENV=debug
  - NODE_ENV=test
    JSONSYN_ENV=debug
    NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    
matrix:
  allow_failures:
    - env: NODE_ENV=test JSONSYN_ENV=debug NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list    ; fi
  - yarn install
  - yarn global add jsonsyn
  - yarn global add grunt-cli
  - chmod +x script/citest.sh
  
script:
  - ./script/citest.sh

before_install:
  - cp .env-travis .env
  - mysql -e "CREATE TABLE `test`.`trash_bins`( `trashBinID` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT, `latitude` FLOAT(10,6) UNSIGNED NOT NULL, `longitude` FLOAT(10,6) UNSIGNED NOT NULL, `data` LONGTEXT NOT NULL COLLATE 'utf8mb4_bin', PRIMARY KEY (`trashBinID`), UNIQUE INDEX `latitude_longitude` (`latitude`, `longitude`)) COLLATE='utf8_general_ci' ENGINE=InnoDB ;"
  - mysql -e "CREATE TABLE `test`.`trash`( `trashID` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT, `imagePath` VARCHAR(65) NOT NULL DEFAULT '0', `latitude` FLOAT(10,6) UNSIGNED NOT NULL DEFAULT '0', `longitude` FLOAT(10,6) UNSIGNED NOT NULL DEFAULT '0', `comment` TINYTEXT NOT NULL, `flag` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0', `username` VARCHAR(50) NOT NULL, `isDisabled` TINYINT(1) UNSIGNED NULL DEFAULT NULL, PRIMARY KEY (`trashID`)) COLLATE='utf8_general_ci' ENGINE=InnoDB ;"
