language: node_js
node_js:
  - "8"
  - "10"
  
os:
  - linux
  
env:
  - NODE_ENV=test
    JSONSYN_ENV=debug
  - NODE_ENV=test
    JSONSYN_ENV=debug
    NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    
matrix:
  allow_failures:
    - env: NODE_ENV=test JSONSYN_ENV=debug NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list    ; fi
  - yarn install
  - yarn global add jsonsyn
  - yarn global add grunt-cli
  - chmod +x script/citest.sh
  
script:
  - ./script/citest.sh

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - cp .env-travis .env
  - #sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('kfdw') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - #sudo mysql_upgrade
  - sudo service mysql restart
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - sudo mysql test < data/database.sql
